// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "Retorna um resultado de quem ganhou",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "result"
                ],
                "summary": "Faz a jogada do jokenpo",
                "parameters": [
                    {
                        "type": "string",
                        "description": "escolha de qual jogada vai fazer (pedra,papel,tesoura)",
                        "name": "escolha",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Resultado",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.Resultado"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.Resultado": {
            "type": "object",
            "properties": {
                "escolhido_pela_maquina": {
                    "type": "string"
                },
                "escolhido_por_voce": {
                    "type": "string"
                },
                "mensagem_de_erro": {
                    "type": "string"
                },
                "resultado": {
                    "$ref": "#/definitions/main.StatusResultado"
                }
            }
        },
        "main.StatusResultado": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "label": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
